# This workflow builds the app and uploads the artifact to github releases whenever a new version tag(e.g., v1.0.0) is pushed to the main branch.

name: Build and Release on Tag

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      # Step 4: Build the package
      - name: Build the package
        run: |
          flet pack src/main.py

      # Step 5: Upload the built package as an artifact
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
