# This workflow builds the app and uploads the artifact to github releases whenever a new version tag(e.g., v1.0.0) is pushed to the main branch.

name: Build and Release on Tag

on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [apk]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install Flet CLI
      - name: Install flet-cli
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli # Use the latest stable version

      # Step 4: Run 'flet build' once to install Flutter/Android SDK
      - name: Install build prerequisites
        run: flet build ${{ matrix.target }} --dry-run

      # Step 5: Accept Android Licenses
      - name: Accept Android Licenses
        run: yes | $HOME/.flet/flutter/bin/flutter doctor --android-licenses

      # Step 6: Build the APK using Flet
      - name: Build APK with Flet
        run: |
          flet build ${{ matrix.target }} --verbose --build-number=${{ github.run_number }} --build-version=${{ github.ref_name }}

      # Step 7: Rename the APK to include version in the filename
      - name: Rename APK
        if: matrix.target == 'apk'
        run: |
          mv build/apk/*.apk build/apk/age-calculator-${{ github.ref_name }}.apk

      # Step 8: Upload the APK as a workflow artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build-artifact
          path: build/${{ matrix.target }}/
          if-no-files-found: error
